export const medicines = [
    {
      id: "M-001",
      name: "AMOXICILLIN",
      discount: "6%",
      price: "12 BTT",
      image: "https://cdn.pixabay.com/photo/2016/02/09/19/45/pills-1190217_1280.jpg",
      availability: "In stock 5",
      productCode: "7464674",
      brand: "Respillin",
      companyEmail: "dennzriush@gmail.com",
      mobile: "0791570615",
      medicineId: "#M-001",
      expiryDate: "2024-10-12",
      manufactureAddress: "6020 Kibirichia 60200 Meru",
      currentLocation: "6020 Kibirichia 60200 Meru",
      manufacturer: "USAntibiotics",
      description: "Amoxicillin is a penicillin antibiotic. It is used to treat bacterial infections, such as chest infections (including pneumonia) and dental abscesses. Often prescribed for children to treat ear infections and chest infections.",
    },
    {
      id: "M-002",
      name: "PENICILLIN",
      discount: "5%",
      price: "10 BTT",
      image: "/penicillin.jpg",
      availability: "In stock 8",
      productCode: "8372941",
      brand: "MediHealth",
      companyEmail: "info@medihealth.com",
      mobile: "0791234567",
      medicineId: "#M-002",
      expiryDate: "2025-05-12",
      manufactureAddress: "123 Pharma St, Nairobi",
      currentLocation: "123 Pharma St, Nairobi",
      manufacturer: "GlobalPharma",
      description: "Penicillin is widely used to treat bacterial infections, including strep throat, scarlet fever, and skin infections. It can prevent bacterial endocarditis and rheumatic fever.",
    },
    {
      id: "M-003",
      name: "CEPHALEXIN",
      discount: "4%",
      price: "15 BTT",
      image: "/cephalexin.jpg",
      availability: "In stock 10",
      productCode: "9654321",
      brand: "HealthCure",
      companyEmail: "support@healthcure.com",
      mobile: "0797654321",
      medicineId: "#M-003",
      expiryDate: "2025-08-19",
      manufactureAddress: "456 Health Blvd, Mombasa",
      currentLocation: "456 Health Blvd, Mombasa",
      manufacturer: "BioGen",
      description: "Cephalexin is used to treat bacterial infections, including respiratory tract, skin, ear, and urinary tract infections. It's often prescribed as an oral antibiotic.",
    },
    {
      id: "M-004",
      name: "AZITHROMYCIN",
      discount: "7%",
      price: "18 BTT",
      image: "/azithromycin.jpg",
      availability: "In stock 6",
      productCode: "3428765",
      brand: "CureFast",
      companyEmail: "contact@curefast.com",
      mobile: "0795671234",
      medicineId: "#M-004",
      expiryDate: "2025-12-10",
      manufactureAddress: "789 Cure Rd, Kisumu",
      currentLocation: "789 Cure Rd, Kisumu",
      manufacturer: "QuickMeds",
      description: "Azithromycin is effective against various bacterial infections, including respiratory and skin infections. It is also used in combination with other antibiotics.",
    },
    {
      id: "M-005",
      name: "CIPROFLOXACIN",
      discount: "3%",
      price: "20 BTT",
      image: "/ciprofloxacin.jpg",
      availability: "In stock 12",
      productCode: "7853429",
      brand: "PharmaPro",
      companyEmail: "sales@pharmapro.com",
      mobile: "0794567890",
      medicineId: "#M-005",
      expiryDate: "2025-06-25",
      manufactureAddress: "789 Medicine Lane, Nakuru",
      currentLocation: "789 Medicine Lane, Nakuru",
      manufacturer: "WellLife",
      description: "Ciprofloxacin is used to treat a variety of bacterial infections, particularly urinary tract infections. It's also effective for respiratory infections and gastrointestinal infections.",
    },
    // Additional medicines can be added here in the same format...
  ];
  